<?php
/**
 * @file
 * testimonials.features.node_export_features.inc
 */

/**
 * Implements hook_node_export_features_default().
 */
function testimonials_node_export_features_default() {
  $node_export = array(
  'code_string' => 'array(
  (object) array(
      \'vid\' => \'150\',
      \'uid\' => \'1\',
      \'title\' => \'Client Feedback\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'1\',
      \'promote\' => \'0\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'c75f31b2-69ee-4b65-a7d6-ff032f3904d4\',
      \'ds_switch\' => \'\',
      \'nid\' => \'150\',
      \'type\' => \'page\',
      \'language\' => \'en\',
      \'created\' => \'1445219572\',
      \'changed\' => \'1445219572\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'ad4b3e35-b63f-4fd4-be7a-9988e6deea5c\',
      \'revision_timestamp\' => \'1445219572\',
      \'revision_uid\' => \'1\',
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => "<div class=\\"client-feedback-page\\">\\r\\n<h2 class=\\"block-title\\">WHY PEOPLE <span class=\\"blue\\">SAY</span></h2>\\r\\n<p class=\\"intermediate-text\\">some information about agency</p>\\r\\n<p class=\\"text\\">As local tour operator we will show you the best places to visit jordan, also this page will guid you what each attractions has to offer.</p>\\r\\n",
            \'summary\' => \'\',
            \'format\' => \'full_html\',
            \'safe_value\' => "<div class=\\"client-feedback-page\\">\\n<h2 class=\\"block-title\\">WHY PEOPLE <span class=\\"blue\\">SAY</span></h2>\\n<p class=\\"intermediate-text\\">some information about agency</p>\\n<p class=\\"text\\">As local tour operator we will show you the best places to visit jordan, also this page will guid you what each attractions has to offer.</p>\\n</div>",
            \'safe_summary\' => \'\',
          ),
        ),
      ),
      \'field_about_company\' => array(),
      \'field_image\' => array(),
      \'cid\' => \'0\',
      \'last_comment_timestamp\' => \'1445219572\',
      \'last_comment_name\' => NULL,
      \'last_comment_uid\' => \'1\',
      \'comment_count\' => \'0\',
      \'name\' => \'administrator\',
      \'picture\' => \'0\',
      \'data\' => \'a:5:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}\',
      \'path\' => array(
        \'pid\' => \'190\',
        \'source\' => \'node/150\',
        \'alias\' => \'client-feedback\',
        \'language\' => \'en\',
      ),
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
)',
);
  return $node_export;
}
